/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libiao_libiaodemo_jni_demo_JNITest */

#ifndef _Included_com_libiao_libiaodemo_jni_demo_JNITest
#define _Included_com_libiao_libiaodemo_jni_demo_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libiao_libiaodemo_jni_demo_JNITest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libiao_libiaodemo_jni_demo_JNITest_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
